version: '3'

services:
  rtsp-server:
    container_name: rtsp-server
    image: rtsp-server
    build: .
    command: python3 main.py
    network_mode: host
    volumes:
      - .:/rtsp-server
    environment:
      - MP4_FILENAME=video_1.mp4
      - DST_STREAM=stream1
    tty: true
    stdin_open: true
    privileged: true